In [65]:
# @title Load Git Repository
# @markdown Clone the Git repository for analysis if needed.
clone_git_repo = False  # @param {type:"boolean"}
if clone_git_repo:
    !git clone https://github.com/PeaceAndLongLife/Analysis-Colab.git
    %cd Analysis-Colab

In [66]:
import sys
from pathlib import Path
sys.path.append(str(Path("src").resolve()))
%cd notebooks

[Errno 2] No such file or directory: 'notebooks'
/content/Analysis-Colab/notebooks

In [67]:
# @title Mount google drive and read in the SERVICE_ACCOUNT_FILE  {"form-width":"20%"}

# @markdown ---
# @markdown
# @markdown The `SERVICE_ACCOUNT_FILE` path is stored as a secret in google colab. If you do not have this sotred on your colab, contact the Admin: Travis Kregear at tkregear@pdx.edu

# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# load SERVICE_ACCOUNT_FIL
from google.colab import userdata

# SERVICE_ACCOUNT_FILE = userdata.get('SERVICE_ACCOUNT_FILE')
SERVICE_ACCOUNT_FILE = '/content/drive/Shareddrives/Travis Research Drive/Interface 3.0/Admin files/service_account.json'

# @title ## Install pyDrive  {"form-width":"20%"}

# @markdown ---
# @markdown Installing PyDrive
# @markdown
# @markdown Thie is necessary if using the Google API to call files by their file_id

# !pip install PyDrive

import sys
# 2. Tell Python to look in your custom folder
# sys.path.append(PACKAGE_PATH)
sys.path.append('src')
# 3. Import your file!
from GoogleFunctions import extract_file_id
from local_io import read_csv_from_id

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Read in data

In [68]:
# @ title ## Input Data Links  {"form-width":"20%"}
# @markdown ---
# Fall data info
# @markdown Read in fall online file {"form-width":"20%"}
fall_online_link = "https://drive.google.com/file/d/1_Gb6kUjWEWFt3pqlI3JJvExPfyvqUB8u/view?usp=drive_link" # @param {"type":"string"}
fall_online_link_id = extract_file_id(fall_online_link)
show_fall_online = False # @param {"type":"boolean"}

# @markdown Read in fall in person file {"form-width":"20%"}
fall_inperson_link = "https://drive.google.com/file/d/12c-U4mECjr3xmjTHNBzbPEYYY5SYM2Cj/view?usp=drive_link" # @param {"type":"string"}
fall_inperson_link_id = extract_file_id(fall_inperson_link)
show_fall_inperson = False # @param {"type":"boolean"}

fall_online_df = read_csv_from_id(SERVICE_ACCOUNT_FILE, fall_online_link_id, show_fall_online)
fall_inperson_df = read_csv_from_id(SERVICE_ACCOUNT_FILE, fall_inperson_link_id, show_fall_inperson)


# @markdown ---
# Winter data info
# @markdown Read in winter online file {"form-width":"20%"}
winter_online_link = "https://drive.google.com/file/d/14zR09W0Tr_lL_wbjAXjtHeWcrmGxAnDd/view?usp=drive_link" # @param {"type":"string"}
winter_online_link_id = extract_file_id(winter_online_link)
show_winter_online = False # @param {"type":"boolean"}

# @markdown Read in fall in person file {"form-width":"20%"}
winter_inperson_link = "https://drive.google.com/file/d/1i4j2ARL1x-FOvDz5gA6gJmxWtT2bHfgk/view?usp=drive_link" # @param {"type":"string"}
winter_inperson_link_id = extract_file_id(winter_inperson_link)
show_winter_inperson = False # @param {"type":"boolean"}

winter_online_df = read_csv_from_id(SERVICE_ACCOUNT_FILE, winter_online_link_id, show_winter_online)
winter_inperson_df = read_csv_from_id(SERVICE_ACCOUNT_FILE, winter_inperson_link_id, show_winter_inperson)

Google Drive API service built successfully.
Reading in csv file. id=1_Gb6kUjWEWFt3pqlI3JJvExPfyvqUB8u
Google Drive API service built successfully.
Reading in csv file. id=12c-U4mECjr3xmjTHNBzbPEYYY5SYM2Cj
Google Drive API service built successfully.
Reading in csv file. id=14zR09W0Tr_lL_wbjAXjtHeWcrmGxAnDd
Google Drive API service built successfully.
Reading in csv file. id=1i4j2ARL1x-FOvDz5gA6gJmxWtT2bHfgk

In [69]:
# @markdown Read in fall in person file {"form-width":"20%"}
userprofile_link = "https://drive.google.com/file/d/1k42GKGxllb97GL7J9q_IFAS0cQ5J4p-c/view?usp=drive_link" # @param {"type":"string"}
userprofile_link_id = extract_file_id(userprofile_link)
show_userprofile = True # @param {"type":"boolean"}

userprofile_df = read_csv_from_id(SERVICE_ACCOUNT_FILE, userprofile_link_id, show_userprofile)
userprofile_df = userprofile_df.rename(columns={'username': 'user'})
user_map = userprofile_df.set_index('user')['id'].squeeze()

Google Drive API service built successfully.
Reading in csv file. id=1k42GKGxllb97GL7J9q_IFAS0cQ5J4p-c

,id,password,last_login,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined,student_id,section,consent_complete,pronouns
0,269,pbkdf2_sha256$1000000$TIL6ZfKAAnQ4GfTnazE6Vm$b...,2026-01-31 07:37:53.645772+00:00,False,abdelqa@pdx.edu,Muhammad-Abdullah,Abdelqader,abdelqa@pdx.edu,False,True,2026-01-04 23:26:34.289747+00:00,949789405,Seth Moriarty (smoriart@pdx.edu),True,he/him
1,103,pbkdf2_sha256$1000000$cwVctt558cnTewu24F4ZcU$X...,2025-12-03 02:17:22.769863+00:00,False,achamber@pdx.edu,Alex,Chambers,achamber@pdx.edu,False,True,2025-09-29 04:53:59.655419+00:00,928955616,Emily Otte (otte@pdx.edu),True,NaN
2,107,pbkdf2_sha256$1000000$RHCVZJCPYP0yPY75LwGZNQ$C...,2025-11-15 07:02:12.581059+00:00,False,achibli@pdx.edu,Aliyah,Chibli,achibli@pdx.edu,False,True,2025-09-29 04:54:02.101070+00:00,971175227,Seth Moriarty (smoriart@pdx.edu),True,NaN
3,270,pbkdf2_sha256$1000000$6DR3YLX9ytbPvaCYEAa0jZ$o...,2026-02-04 02:17:54.189280+00:00,False,adenand@pdx.edu,Aden,Anderson,adenand@pdx.edu,False,True,2026-01-04 23:26:34.556721+00:00,908388282,Emily Otte (otte@pdx.edu),True,"he/him, they/them"
4,267,pbkdf2_sha256$1000000$061odHoVw8X4gedEM85MW0$k...,2025-12-09 17:29:42.145293+00:00,False,adnan4@pdx.edu,Adnan,Alabbas,adnan4@pdx.edu,False,True,2025-11-14 22:26:49.258931+00:00,933953157,Emily Otte (otte@pdx.edu),True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,92,pbkdf2_sha256$1000000$Ff7vRoSTmoBsKkNnC2hHFN$x...,2025-11-25 19:31:40.749936+00:00,False,yurib@pdx.edu,Yuri,Bogarin Cruz,yurib@pdx.edu,False,True,2025-09-29 04:53:53.111400+00:00,950812093,Andrew Holley (holleyan@pdx.edu),True,she/her
283,205,pbkdf2_sha256$1000000$BSA06DdjPpEfI8mQsvNeTM$b...,2025-11-19 22:43:59.169663+00:00,False,yuris@pdx.edu,Yuri,Sato-Duncan,yuris@pdx.edu,False,True,2025-09-29 04:55:01.050289+00:00,988664205,Emily Otte (otte@pdx.edu),True,she/her
284,79,pbkdf2_sha256$1000000$J9rAZaBpqbplOhGHVALHpS$+...,2026-01-29 22:35:50.344834+00:00,False,zackabdu@pdx.edu,Zakaria,Abdussamad,zackabdu@pdx.edu,False,True,2025-09-29 04:53:44.878210+00:00,941206838,Andrew Holley (holleyan@pdx.edu),True,NaN
285,133,pbkdf2_sha256$1000000$sNGUp2L7C1TrtPOxIFQOOC$j...,2025-12-03 03:21:50.772436+00:00,False,zhegwer@pdx.edu,Zoe,Hegwer,zhegwer@pdx.edu,False,True,2025-09-29 04:54:17.783874+00:00,943246768,Andrew Holley (holleyan@pdx.edu),True,she/her
286,261,pbkdf2_sha256$1000000$Wx5W2IrVouKS4EFfykvT8U$w...,2026-02-05 05:09:22.962943+00:00,False,ztaher@pdx.edu,Ziyad,Taher,ztaher@pdx.edu,False,True,2025-10-05 04:17:50.919297+00:00,973071891,Ryan McGraw (rmcgraw@pdx.edu),True,NaN

In [70]:
display(user_map)

user
abdelqa@pdx.edu     269
achamber@pdx.edu    103
achibli@pdx.edu     107
adenand@pdx.edu     270
adnan4@pdx.edu      267
                   ...
yurib@pdx.edu        92
yuris@pdx.edu       205
zackabdu@pdx.edu     79
zhegwer@pdx.edu     133
ztaher@pdx.edu      261
Name: id, Length: 287, dtype: int64

In [71]:
def strip_id(df):
    if 'login_id' in df.columns:
        df['user'] = df['login_id'] + '@pdx.edu'
        # df = df.drop(df.iloc[[0, 1]].index)
        df['user'] = df['user'].map(user_map).fillna(pd.NA).astype('Int64')
        # df.set_index('user', inplace=True)
    return df
fall_online_stripped_df = strip_id(fall_online_df)
fall_online_stripped_df = fall_online_stripped_df.drop(columns=['name', 'login_id', 'canvas_user_id'])
display(fall_online_stripped_df)

fall_inperson_stripped_df = strip_id(fall_inperson_df)  
fall_inperson_stripped_df = fall_inperson_stripped_df.drop(columns=['name', 'login_id', 'canvas_user_id']) 
display(fall_inperson_stripped_df)

winter_online_stripped_df = strip_id(winter_online_df)
winter_online_stripped_df = winter_online_stripped_df.drop(columns=['name', 'login_id', 'canvas_user_id'])
display(winter_online_stripped_df)

winter_inperson_stripped_df = strip_id(winter_inperson_df)
winter_inperson_stripped_df = winter_inperson_stripped_df.drop(columns=['name', 'login_id', 'canvas_user_id'])
display(winter_inperson_stripped_df)

,sections,group_name,canvas_group_id,user
0,PH-214-001: Lab For Ph 201/211/221/231,Ryan McGraw (rmcgraw@pdx.edu),75644,78
1,PH-214-001: Lab For Ph 201/211/221/231,Cassandra Croft (croft@pdx.edu),75643,79
2,PH-214-001: Lab For Ph 201/211/221/231,Seth Moriarty (smoriart@pdx.edu),75645,264
3,PH-214-001: Lab For Ph 201/211/221/231,Emily Otte (otte@pdx.edu),75648,267
4,PH-214-001: Lab For Ph 201/211/221/231,Andrew Holley (holleyan@pdx.edu),75646,80
...,...,...,...,...
140,PH-214-001: Lab For Ph 201/211/221/231,Emily Otte (otte@pdx.edu),75648,241
141,PH-214-001: Lab For Ph 201/211/221/231,Andrew Holley (holleyan@pdx.edu),75646,243
142,PH-214-001: Lab For Ph 201/211/221/231,Elizabeth Hillman (elizabeh@pdx.edu),75647,244
143,PH-214-001: Lab For Ph 201/211/221/231,Andrew Holley (holleyan@pdx.edu),75646,245
144,PH-214-001: Lab For Ph 201/211/221/231,Andrew Holley (holleyan@pdx.edu),75646,246

                                   sections  group_name  user
0    PH-214-002: Lab For Ph 201/211/221/231         NaN   287
1     PH-214-W3: Lab For Ph 201/211/221/231         NaN  <NA>
2     PH-214-T4: Lab For Ph 201/211/221/231         NaN   322
3     PH-214-T4: Lab For Ph 201/211/221/231         NaN  <NA>
4     PH-214-F1: Lab For Ph 201/211/221/231         NaN  <NA>
..                                      ...         ...   ...
257   PH-214-F2: Lab For Ph 201/211/221/231         NaN  <NA>
258  PH-214-002: Lab For Ph 201/211/221/231         NaN  <NA>
259   PH-214-F2: Lab For Ph 201/211/221/231         NaN  <NA>
260   PH-214-T4: Lab For Ph 201/211/221/231         NaN  <NA>
261   PH-214-T4: Lab For Ph 201/211/221/231         NaN  <NA>

[262 rows x 3 columns]

,sections,group_name,canvas_group_id,user
0,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,287
1,PH-215-001: Lab For Ph 202/212/222/232,Seth Moriarty (smoriart@pdx.edu),80965,269
2,PH-215-001: Lab For Ph 202/212/222/232,Seth Moriarty (smoriart@pdx.edu),80965,322
3,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,79
4,PH-215-001: Lab For Ph 202/212/222/232,Emily Otte (otte@pdx.edu),80963,307
...,...,...,...,...
123,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,239
124,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,241
125,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,324
126,PH-215-001: Lab For Ph 202/212/222/232,Elizabeth Hillman (elizabeh@pdx.edu),80962,244
127,PH-215-001: Lab For Ph 202/212/222/232,Elizabeth Hillman (elizabeh@pdx.edu),80962,246

                                   sections  group_name  user
0    PH-215-W01: Lab For Ph 202/212/222/232         NaN  <NA>
1    PH-215-R02: Lab For Ph 202/212/222/232         NaN  <NA>
2    PH-215-W02: Lab For Ph 202/212/222/232         NaN  <NA>
3    PH-215-W01: Lab For Ph 202/212/222/232         NaN  <NA>
4    PH-215-F02: Lab For Ph 202/212/222/232         NaN  <NA>
..                                      ...         ...   ...
206  PH-215-F02: Lab For Ph 202/212/222/232         NaN  <NA>
207  PH-215-W02: Lab For Ph 202/212/222/232         NaN   243
208  PH-215-W02: Lab For Ph 202/212/222/232         NaN   245
209  PH-215-R02: Lab For Ph 202/212/222/232         NaN  <NA>
210  PH-215-R02: Lab For Ph 202/212/222/232         NaN  <NA>

[211 rows x 3 columns]

In [74]:
import pandas as pd


def compare_users_in_df(df1,df2,col):


    # display(df1,df2)
    # This returns rows from df1 where the name is also present in df2
    common_names = df1[df1[col].isin(df2[col])]

    print("\nRows in that match:")
    display(common_names)

print("fall_online to winter_inperson")
compare_users_in_df(winter_inperson_stripped_df,fall_online_stripped_df,'user')
print("\n---\n")

print("fall_inperson to winter_online")
compare_users_in_df(winter_online_stripped_df,fall_inperson_stripped_df,'user')
print("\n---\n")

fall_online to winter_inperson

Rows in that match:

                                   sections  group_name  user
21   PH-215-F02: Lab For Ph 202/212/222/232         NaN    85
24   PH-215-F01: Lab For Ph 202/212/222/232         NaN    90
28   PH-215-W02: Lab For Ph 202/212/222/232         NaN    92
38   PH-215-T01: Lab For Ph 202/212/222/232         NaN    98
41   PH-215-R02: Lab For Ph 202/212/222/232         NaN   101
53   PH-215-F02: Lab For Ph 202/212/222/232         NaN   111
54   PH-215-F01: Lab For Ph 202/212/222/232         NaN   112
68   PH-215-W02: Lab For Ph 202/212/222/232         NaN   121
80   PH-215-R01: Lab For Ph 202/212/222/232         NaN   133
111  PH-215-R02: Lab For Ph 202/212/222/232         NaN   147
114  PH-215-F02: Lab For Ph 202/212/222/232         NaN   149
126  PH-215-F01: Lab For Ph 202/212/222/232         NaN   162
142  PH-215-R02: Lab For Ph 202/212/222/232         NaN   177
143  PH-215-F01: Lab For Ph 202/212/222/232         NaN   180
147  PH-215-F01: Lab For Ph 202/212/222/232         NaN   187
153  PH-215-F01: Lab For Ph 202/212/222/232         NaN   196
165  PH-215-R01: Lab For Ph 202/212/222/232         NaN   207
189  PH-215-T01: Lab For Ph 202/212/222/232         NaN   223
201  PH-215-T01: Lab For Ph 202/212/222/232         NaN   240
207  PH-215-W02: Lab For Ph 202/212/222/232         NaN   243
208  PH-215-W02: Lab For Ph 202/212/222/232         NaN   245

---

fall_inperson to winter_online

Rows in that match:

,sections,group_name,canvas_group_id,user
0,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,287
2,PH-215-001: Lab For Ph 202/212/222/232,Seth Moriarty (smoriart@pdx.edu),80965,322
7,PH-215-001: Lab For Ph 202/212/222/232,Emily Otte (otte@pdx.edu),80963,270
9,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,319
15,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,273
23,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,305
31,PH-215-001: Lab For Ph 202/212/222/232,Seth Moriarty (smoriart@pdx.edu),80965,311
32,PH-215-001: Lab For Ph 202/212/222/232,Seth Moriarty (smoriart@pdx.edu),80965,310
33,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,328
38,PH-215-001: Lab For Ph 202/212/222/232,Ryan McGraw (rmcgraw@pdx.edu),80964,308
40,PH-215-001: Lab For Ph 202/212/222/232,Seth Moriarty (smoriart@pdx.edu),80965,293
43,PH-215-001: Lab For Ph 202/212/222/232,Seth Moriarty (smoriart@pdx.edu),80965,313
45,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,271
52,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,306
57,PH-215-001: Lab For Ph 202/212/222/232,Elizabeth Hillman (elizabeh@pdx.edu),80962,318
59,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,295
62,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,281
66,PH-215-001: Lab For Ph 202/212/222/232,Emily Otte (otte@pdx.edu),80963,299
71,PH-215-001: Lab For Ph 202/212/222/232,Emily Otte (otte@pdx.edu),80963,334
82,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,291
83,PH-215-001: Lab For Ph 202/212/222/232,Elizabeth Hillman (elizabeh@pdx.edu),80962,290
84,PH-215-001: Lab For Ph 202/212/222/232,Ryan McGraw (rmcgraw@pdx.edu),80964,312
85,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,301
86,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,284
90,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,279
94,PH-215-001: Lab For Ph 202/212/222/232,Seth Moriarty (smoriart@pdx.edu),80965,327
97,PH-215-001: Lab For Ph 202/212/222/232,Cassandra Croft (croft@pdx.edu),80960,285
99,PH-215-001: Lab For Ph 202/212/222/232,Andrew Holley (holleyan@pdx.edu),80961,275
102,PH-215-001: Lab For Ph 202/212/222/232,Ryan McGraw (rmcgraw@pdx.edu),80964,296
119,PH-215-001: Lab For Ph 202/212/222/232,Emily Otte (otte@pdx.edu),80963,283
121,PH-215-001: Lab For Ph 202/212/222/232,Emily Otte (otte@pdx.edu),80963,280

---